### PR TITLE
Changes by adam and me.

### PR DESCRIPTION
**Pull request by hanss314**
I added my code along with adamthedog's to your better looking files. Also changed the one line `elseif`s for clearer reading and removed the double indentations on some parts.

### CODE REVIEW

**Comment by Chronophylos** [comment]
I will merge this when I get home

**Comment by hanss314** [comment]
Thx

**Comment by hanss314** [comment]
Yoylecake!

**Comment by Chronophylos** [comment]
Nevermind had time in school. I couldn't test anything yet.

**Pull request merged**
